package:
  name: mathlab
  version: '0.1.1'

source:
  git_url: https://github.com/decarlof/mathlab.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - scipy
    - numpy    
    
test:
  # Python imports
  imports:
    - mathlab
    - mathlab.geometry

about:
  home: http://mathlab.readthedocs.org
  license: BSD-3
  summary: 'Add docs to any project.'
